env:
  - PLATFORM=debian-jessie
  - PLATFORM=debian-stretch

sudo: required

language: python

services:
  - docker

install:
  - docker build -f tests/$PLATFORM.Dockerfile -t test-$PLATFORM .

script:
  - docker run --name $PLATFORM test-$PLATFORM
