---

- name: ASSERT | Check Debian version 
  assert:
    that:
      - "ansible_distribution_major_version >= 8 and ansible_distribution == 'Debian'"

- name: INCLUDE | Jessie related
  include: jessie.yml
  when: ansible_distribution_release == 'jessie'

- name: APT | Install s3fs and necessary packages
  apt: pkg=s3fs update_cache=yes cache_valid_time=3600 state=present
  
- name: APT | Install ohai
  apt: pkg=ohai
  register: ohai

- name: SETUP
  action: setup
  when: ohai.changed

- name: FILE | Create mount directory
  file: >
    path={{ item.dir }}
    state=directory
  with_items: s3_mounts

- name: TEMPLATE | Add AWS credentials
  template: >
    src=etc/passwd-s3fs.j2
    dest=/etc/passwd-s3fs
    mode=0640
    owner=root
    group=root
  register: credentials

- name: MOUNT | all buckets
  mount: >
    name='{{ item.dir }}'
    src='s3fs#{{ item.bucket }}'
    fstype='fuse'
    state='mounted'
    opts="_netdev,{% if item.owner is defined %}uid={{ ohai_etc.passwd[item.owner].uid }},{% endif %}{% if item.group is defined %}gid={{ ohai_etc.group[item.group].gid }},{% endif %}{% for o in item.mount_options | default([]) %}{{ o.key }}{% if o.value is defined %}={{ o.value }}{% endif %}{% if not loop.last %},{% endif %}{% endfor %}"
  with_items: s3_mounts
